version: '3'

services: 
    review:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - ..:/workspace:cached

        tty: true
        # command: sleep infinity